name = "msourceio-inquiry"

# Publishing to workers.dev for quick testing
workers_dev = true

main = "./worker/worker.mjs"

[build]
  command = ""

[vars]
INQUIRY_TO_EMAIL = "1476080750@qq.com,annliao@msourceio.com"
EMAIL_PROVIDER = "mailchannels"
